stderr of test 'wlr40` in directory 'sql/test/wlcr` itself:


# 13:02:55 >  
# 13:02:55 >  "/usr/bin/python2" "wlr40.py" "wlr40"
# 13:02:55 >  

# builtin opt 	gdk_dbpath = /export/scratch1/mk/wlcr//Linux/var/monetdb5/dbfarm/demo
# builtin opt 	gdk_debug = 0
# builtin opt 	gdk_vmtrim = no
# builtin opt 	monet_prompt = >
# builtin opt 	monet_daemon = no
# builtin opt 	mapi_port = 50000
# builtin opt 	mapi_open = false
# builtin opt 	mapi_autosense = false
# builtin opt 	sql_optimizer = default_pipe
# builtin opt 	sql_debug = 0
# cmdline opt 	gdk_nr_threads = 0
# cmdline opt 	mapi_open = true
# cmdline opt 	mapi_port = 47971
# cmdline opt 	mapi_usock = /var/tmp/mtest-32073/.s.monetdb.47971
# cmdline opt 	gdk_dbpath = /export/scratch1/mk/branches/wlcr//Linux/var/MonetDB/mTests_sql_test_wlcr-clone
#client1:!ERROR:MALException:sql.replicate:Replicator not started, call setmaster() first 
MAPI  = (monetdb) /var/tmp/mtest-32073/.s.monetdb.47971
QUERY = call wlr.replicate(9);
ERROR = !Replicator not started, call wlr.master() first 

# 13:02:55 >  
# 13:02:55 >  "Done."
# 13:02:55 >  

