stderr of test 'wlr70` in directory 'sql/test/wlcr` itself:


# 13:16:46 >  
# 13:16:46 >  "/bin/python2" "wlr70.py" "wlr70"
# 13:16:46 >  

# builtin opt 	gdk_dbpath = /home/kutsurak/work/monet/sources/MonetDB/build/install/var/monetdb5/dbfarm/demo
# builtin opt 	gdk_debug = 0
# builtin opt 	gdk_vmtrim = no
# builtin opt 	monet_prompt = >
# builtin opt 	monet_daemon = no
# builtin opt 	mapi_port = 50000
# builtin opt 	mapi_open = false
# builtin opt 	mapi_autosense = false
# builtin opt 	sql_optimizer = default_pipe
# builtin opt 	sql_debug = 0
# cmdline opt 	gdk_nr_threads = 0
# cmdline opt 	mapi_open = true
# cmdline opt 	mapi_port = 32871
# cmdline opt 	mapi_usock = /var/tmp/mtest-22885/.s.monetdb.32871
# cmdline opt 	gdk_dbpath = /export/scratch1/mk/branches/wlcr//Linux/var/MonetDB/mTests_sql_test_wlcrclone
#time limit 2019-10-04 20:55:58.392
#client1:!ERROR:SQLException:wlr.startreplicate:42000!Timeout to wait for replicator to catch up.Catched up until 8, 9223372036854775799 pending
MAPI  = (monetdb) /var/tmp/mtest-22885/.s.monetdb.32871
QUERY = call wlr.replicate(now());
ERROR = !Timeout to wait for replicator to catch up.Catched up until 8, 9223372036854775799 pending
CODE  = 42000

# 13:16:48 >  
# 13:16:48 >  "Done."
# 13:16:48 >  

